### ISSUE TITLE
Tracking Issue Landing Page

### ISSUE THREAD

**Issue by donavinlo** [donavinlo/rhythm_package#2]

**Comment by donavinlo** [comment]
- [ ] Go through setuputils setup
- [ ] Create Virtual Environment
- [ ] Push to git with .gitignore
- [ ] Create thins

**Comment by donavinlo** [comment]
#Eat Me
- [ ] fdfgdfgd
- [ ] hdjhgjhgf

#Heck No
- [ ] kgjhghjg
